services:
  gateway:
    image: nitsvutt/gateway:1.0.0
    hostname: gateway
    ports:
      - "8977:8977"
    volumes:
      - $COMMON_PATH/spark/event:/opt/spark/event
      - $COMMON_PATH/spark/work:/opt/spark/work
      - $PROJECT_PATH/lakehouse-platform/workspace:/project
    environment:
      - SPARK_MODE=client
      - PRODUCT1_SERVER=$PRODUCT1_SERVER
      - PRODUCT1_PORT=$PRODUCT1_PORT
      - PRODUCT1_USER=$PRODUCT1_USER
      - PRODUCT1_PASSWORD=$PRODUCT1_PASSWORD
    command: jupyter notebook --no-browser --NotebookApp.token 'password' --ip 0.0.0.0 --port 8977 --allow-root
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true