services:
  trino-coordinator:
    image: 'trinodb/trino:476'
    ports:
      - '8180:8080'
    volumes:
      - $PROJECT_PATH/lakehouse-platform/trino/etc/coordinator:/etc/trino
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      PRODUCT2_SERVER: $PRODUCT2_SERVER
      PRODUCT2_PORT: $PRODUCT2_PORT
      PRODUCT2_USER: $PRODUCT2_USER
      PRODUCT2_PASSWORD: $PRODUCT2_PASSWORD
    networks:
      - lakehouse_platform

  trino-worker:
    image: 'trinodb/trino:476'
    volumes:
      - $PROJECT_PATH/lakehouse-platform/trino/etc/worker:/etc/trino
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      PRODUCT2_SERVER: $PRODUCT2_SERVER
      PRODUCT2_PORT: $PRODUCT2_PORT
      PRODUCT2_USER: $PRODUCT2_USER
      PRODUCT2_PASSWORD: $PRODUCT2_PASSWORD
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true