services:
  product1-db:
    image: postgres:15-alpine3.18
    hostname: product1-db
    ports:
      - "5433:5433"
    volumes:
      - $COMMON_PATH/product1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$PRODUCT1_USER
      - POSTGRES_PASSWORD=$PRODUCT1_PASSWORD
      - POSTGRES_DB=product1
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=5433
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    networks:
      - lakehouse_platform
  
  product1:
    image: nitsvutt/fastapi-python:3.10.4
    hostname: product1
    depends_on:
      - product1-db
    ports:
      - "8901:8901"
    volumes:
      - .:/app
    environment:
      PRODUCT1_SERVER: $PRODUCT1_SERVER
      PRODUCT1_PORT: $PRODUCT1_PORT
      PRODUCT1_USER: $PRODUCT1_USER
      PRODUCT1_PASSWORD: $PRODUCT1_PASSWORD
    command: uvicorn main:product1 --host 0.0.0.0 --port 8901 --reload
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true