services:
  scylla-node1:
    image: scylladb/scylla:5.4.2
    container_name: scylla-node1
    command: |
      --seeds scylla-node1,scylla-node2
      --broadcast-rpc-address scylla-node1 \
      --broadcast-address scylla-node1 \
      --smp 1 --memory 1G --cpuset 1
    volumes:
      - $COMMON_PATH/scylladb/data1:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/scylla-mdc.yaml:/etc/scylla/scylla.yaml
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
    ports:
      - 17000:7000
      - 17001:7001
      - 17199:7199
    networks:
      - lakehouse_platform
  
  scylla-node2:
    image: scylladb/scylla:5.4.2
    container_name: scylla-node2
    command: |
      --seeds scylla-node1,scylla-node2
      --broadcast-rpc-address scylla-node2 \
      --broadcast-address scylla-node2 \
      --smp 1 --memory 1G --cpuset 2
    volumes:
      - $COMMON_PATH/scylladb/data2:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/scylla-mdc.yaml:/etc/scylla/scylla.yaml
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
    ports:
      - 27000:7000
      - 27001:7001
      - 27199:7199
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true