services:
  scylla-node3:
    image: scylladb/scylla:5.4.2
    container_name: scylla-node3
    command: |
      --seeds scylla-node1,scylla-node2
      --broadcast-rpc-address scylla-node3 \
      --broadcast-address scylla-node3 \
      --smp 1 --memory 1G --cpuset 3
    volumes:
      - $COMMON_PATH/scylladb/data3:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/scylla-mdc.yaml:/etc/scylla/scylla.yaml
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/cassandra-rackdc-mdc.properties:/etc/scylla/cassandra-rackdc.properties
    ports:
      - 37000:7000
      - 37001:7001
      - 37199:7199
    networks:
      - lakehouse_platform
  
  scylla-node4:
    image: scylladb/scylla:5.4.2
    container_name: scylla-node4
    command: |
      --seeds scylla-node1,scylla-node2
      --broadcast-rpc-address scylla-node4 \
      --broadcast-address scylla-node4 \
      --smp 1 --memory 1G --cpuset 4
    volumes:
      - $COMMON_PATH/scylladb/data4:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/scylla-mdc.yaml:/etc/scylla/scylla.yaml
      - $PROJECT_PATH/lakehouse-platform/scylladb/config/cassandra-rackdc-mdc.properties:/etc/scylla/cassandra-rackdc.properties
    ports:
      - 47000:7000
      - 47001:7001
      - 47199:7199
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true